# Generated by Django 4.1 on 2024-06-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="data",
            options={"verbose_name_plural": "Data"},
        ),
    ]
