# Generated by Django 4.1 on 2024-06-22 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_region_data_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="Regions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("population", models.PositiveIntegerField(null=True)),
            ],
            options={
                "verbose_name_plural": "Regions",
            },
        ),
        migrations.RemoveField(
            model_name="data",
            name="region",
        ),
        migrations.DeleteModel(
            name="Region",
        ),
        migrations.AddField(
            model_name="regions",
            name="data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regions",
                to="dashboard.data",
            ),
        ),
    ]
