# Generated by Django 4.1 on 2024-06-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_regions_remove_data_region_delete_region_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ecoles",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lat", models.FloatField(default=0)),
                ("long", models.FloatField(default=0)),
            ],
            options={
                "verbose_name_plural": "Ecoles",
            },
        ),
    ]
