# Generated by Django 4.1 on 2024-06-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_ecoles"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecoles",
            name="ville",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
